### PR TITLE
Jw friends list

### PR DESCRIPTION
**Pull request by josephwalker504**
# Description
git fetch --all 
git checkout jw-friends-list

nothing fancy just pushing up my code to ensure everybody has my latest code

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by melliemuse** [comment]
I'm getting merge conflicts when I'm trying to look at your branch- I'm wondering if you have the latest version of master merged into your branch?

**Review by melliemuse — DISMISSED** [review]
Looks great- nice job!

**Comment by melliemuse** [comment]
Looks great!

**Review by melliemuse — APPROVED** [review]
Looks great! Nice job!

**Review by rhc822 — APPROVED** [review]
Stuff shows up as expected and no red in DOM, sweet

**Pull request merged**
