### PR TITLE
Created the file structure and created the event HTML form that will …

### PR DESCRIPTION
**Pull request by rhc822**
# Description

I have created the file structure (modules) for the events. Also, in the formBuilderAndEditor.js module, I created three functions:

1) newEventButton
2) newEventFormBuilder
3) editEventFormBuilder

In the console, you should be able to see these functions as objects within the eventsFormBuilder variable.

As a side note, I commented out a lot of our console logs to avoid having a bunch of stuff in the console (we could consider removing them).

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

- git fetch --all
- git checkout event-list-build-form
- Check to see if the code in formBuilderAndEditor.js makes sense and looks good
- Also, check that that info shows up in the console

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by josephwalker504 — DISMISSED** [review]
all modules are there and console log

**Review by CassieBoyd — DISMISSED** [review]
Everything is showing up in the console- looks good!

**Comment by melliemuse** [comment]
Mainly looks good- would pass in an object and use string interpolation in the edit form to populate it with info to edit including adding event-to-edit's id to the button and article ids

**Review by CassieBoyd — DISMISSED** [review]
Everything's showing up in the console- good work!

**Review by CassieBoyd — APPROVED** [review]
Third time's the charm!

**Review by melliemuse — APPROVED** [review]
Looks good- nice job!

**Pull request merged**
